version:  '3.7'
services:
  db:
    image: mysql:8.0
    restart: on-failure
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DB_PORT}:3306
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql:rw

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    container_name: nginx
    volumes:
      - ./app/public:/app/symfony:rw,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    env_file:
      - .env
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    restart: on-failure
    volumes:
      - ./app:/app/symfony:rw,cached
    env_file:
      - .env
    user: ${LOCAL_USER}
    depends_on:
      - db
      - redis

  redis:
    image: redis
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}

volumes:
  db-data: # If we delete mysql image, the previous build db is not lost