version:  '3.7'
services:
  db:
    image: mysql:8.0
    restart: on-failure
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql:rw
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    container_name: nginx
    volumes:
      - ./apps/rbnb/public/:/usr/src/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    restart: on-failure
    volumes:
      - ./apps/rbnb:/usr/src/app:rw,cached
      - ./logs/php:/var/log/php
    env_file:
      - .env
    user: 1000:1000
    depends_on:
      - db
      - redis
  redis:
    image: redis
    expose:
      - 6379

volumes:
  db-data: {} # If we delete mysql image, the previous build db is not lost